# Generated by Django 5.0.6 on 2024-07-02 04:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("riot_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TeamRanking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("team_logo", models.URLField()),
                ("team_name", models.CharField(max_length=100)),
                ("wins", models.IntegerField()),
                ("losses", models.IntegerField()),
                ("points", models.IntegerField()),
            ],
        ),
    ]
