# Generated by Django 5.0.6 on 2024-07-02 04:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("riot_app", "0002_teamranking"),
    ]

    operations = [
        migrations.AddField(
            model_name="teamranking",
            name="rank",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="teamranking",
            name="season",
            field=models.CharField(default="2024 LCK 서머", max_length=100),
        ),
    ]
