# Generated by Django 5.0.6 on 2024-07-02 05:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("riot_app", "0003_teamranking_rank_teamranking_season"),
    ]

    operations = [
        migrations.AddField(
            model_name="teamranking",
            name="assists",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="teamranking",
            name="deaths",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="teamranking",
            name="kda",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="teamranking",
            name="kills",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="teamranking",
            name="win_rate",
            field=models.FloatField(default=0.0),
        ),
    ]
