# Generated by Django 5.0.6 on 2024-07-02 12:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "riot_app",
            "0006_champion_championimage_championinfo_championpassive_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="championskin",
            name="champion",
        ),
        migrations.RemoveField(
            model_name="championstat",
            name="champion",
        ),
        migrations.RemoveField(
            model_name="championimage",
            name="champion",
        ),
        migrations.RemoveField(
            model_name="championpassive",
            name="champion",
        ),
        migrations.RemoveField(
            model_name="championinfo",
            name="champion",
        ),
        migrations.RemoveField(
            model_name="championspell",
            name="champion",
        ),
        migrations.RemoveField(
            model_name="passiveimage",
            name="passive",
        ),
        migrations.RemoveField(
            model_name="spellimage",
            name="spell",
        ),
        migrations.RemoveField(
            model_name="game",
            name="teams",
        ),
        migrations.RemoveField(
            model_name="player",
            name="team",
        ),
        migrations.DeleteModel(
            name="TeamRanking",
        ),
        migrations.DeleteModel(
            name="ChampionSkin",
        ),
        migrations.DeleteModel(
            name="ChampionStat",
        ),
        migrations.DeleteModel(
            name="ChampionImage",
        ),
        migrations.DeleteModel(
            name="ChampionInfo",
        ),
        migrations.DeleteModel(
            name="Champion",
        ),
        migrations.DeleteModel(
            name="ChampionPassive",
        ),
        migrations.DeleteModel(
            name="PassiveImage",
        ),
        migrations.DeleteModel(
            name="ChampionSpell",
        ),
        migrations.DeleteModel(
            name="SpellImage",
        ),
        migrations.DeleteModel(
            name="Game",
        ),
        migrations.DeleteModel(
            name="Player",
        ),
        migrations.DeleteModel(
            name="Team",
        ),
    ]
