# Generated by Django 5.0.6 on 2024-07-02 12:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Champion",
            fields=[
                ("key", models.CharField(max_length=100)),
                (
                    "id",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=100)),
                ("title", models.CharField(max_length=100)),
                ("lore", models.TextField()),
                ("blurb", models.TextField()),
                ("allytips", models.TextField()),
                ("enemytips", models.TextField()),
                ("tags", models.CharField(max_length=100)),
                ("partype", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="ChampionImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full", models.CharField(max_length=100)),
                ("sprite", models.CharField(max_length=100)),
                ("group", models.CharField(max_length=100)),
                ("x", models.IntegerField()),
                ("y", models.IntegerField()),
                ("W", models.IntegerField()),
                ("h", models.IntegerField()),
                (
                    "champion",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="model_champion.champion",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ChampionInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("attack", models.IntegerField()),
                ("defense", models.IntegerField()),
                ("magic", models.IntegerField()),
                ("difficulty", models.IntegerField()),
                (
                    "champion",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="model_champion.champion",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ChampionPassive",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField()),
                (
                    "champion",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="model_champion.champion",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ChampionSkin",
            fields=[
                (
                    "id",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                ("num", models.IntegerField()),
                ("name", models.CharField(max_length=100)),
                ("chromas", models.BooleanField()),
                (
                    "champion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="model_champion.champion",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ChampionSpell",
            fields=[
                (
                    "id",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("tooltip", models.TextField()),
                ("maxrank", models.IntegerField()),
                ("cooldown", models.TextField()),
                ("cooldownBurn", models.CharField(max_length=100)),
                ("cost", models.TextField()),
                ("costBurn", models.CharField(max_length=100)),
                ("costType", models.CharField(max_length=100)),
                ("range", models.TextField()),
                ("resource", models.CharField(blank=True, max_length=100)),
                (
                    "champion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="model_champion.champion",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ChampionStat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("hp", models.FloatField()),
                ("hpperlevel", models.FloatField()),
                ("mp", models.FloatField()),
                ("mpperlevel", models.FloatField()),
                ("movespeed", models.FloatField()),
                ("armor", models.FloatField()),
                ("armorperlevel", models.FloatField()),
                ("spellblock", models.FloatField()),
                ("spellblockperlevel", models.FloatField()),
                ("attackrange", models.FloatField()),
                ("hpregen", models.FloatField()),
                ("hpregenperlevel", models.FloatField()),
                ("mpregen", models.FloatField()),
                ("mpregenperlevel", models.FloatField()),
                ("crit", models.FloatField()),
                ("critperlevel", models.FloatField()),
                ("attackdamage", models.FloatField()),
                ("attackdamageperlevel", models.FloatField()),
                ("attackspeedperlevel", models.FloatField()),
                ("attackspeed", models.FloatField()),
                (
                    "champion",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="model_champion.champion",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PassiveImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full", models.CharField(max_length=100)),
                ("sprite", models.CharField(max_length=100)),
                ("group", models.CharField(max_length=100)),
                ("x", models.IntegerField()),
                ("y", models.IntegerField()),
                ("W", models.IntegerField()),
                ("h", models.IntegerField()),
                (
                    "passive",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="model_champion.championpassive",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SpellImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full", models.CharField(max_length=100)),
                ("sprite", models.CharField(max_length=100)),
                ("group", models.CharField(max_length=100)),
                ("x", models.IntegerField()),
                ("y", models.IntegerField()),
                ("W", models.IntegerField()),
                ("h", models.IntegerField()),
                (
                    "spell",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="model_champion.championspell",
                    ),
                ),
            ],
        ),
    ]
